ALLREVA/Allreva_FE

.storybook/preview.tsx, eslint.config.js, src/components/buttons/BaseButton.stories.tsx, src/components/buttons/BaseButton.tsx, src/components/buttons/types.ts
Base Button 컴포넌트 구현
</br>
</br>
- storybook preview.tsx에 스토리북 전역 style 추가
- eslint 설정 추가
</br>
</br>
</br>
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #14
=> [ARV-43] Base Button 컴포넌트 구현

src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx
`Checkbox` 컴포넌트 및 스토리북 구현
</br>
</br>
- components/Checkbox
</br>
</br>
</br>
</br>
- Close #15
=> [ARV-44] Checkbox 컴포넌트 구현

src/components/radioButton/RadioButton.stories.tsx, src/components/radioButton/RadioButton.tsx
RadioButton 컴포넌트 구현
</br>
</br>
- components/radioButton
</br>
</br>
</br>
UI 변경 사항이 있거나 테스트 관련 스크린샷이 필요한 경우 추가해 주세요.
</br>
- Closes #20
=> [ARV-48] RadioButton 컴포넌트 구현

.storybook/preview.tsx, src/styles/GlobalStyle.tsx
Storybook 로컬 폰트 적용
</br>
</br>
- Storybook 로컬 폰트 적용
- Global Style font-face -> import
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #24
=> [ARV-52] Storybook 로컬 폰트 적용

.storybook/preview.tsx, src/components/chips/FilterChip.stories.tsx, src/components/chips/FilterChip.tsx, src/components/chips/SimpleChip.stories.tsx, src/components/chips/SimpleChip.tsx
Chip 컴포넌트 구현
</br>
</br>
- storybook 뷰포트 설정 변경
- SimpleChip, FilterChip 컴포넌트 추가
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #29
=> [ARV-56] Chip 컴포넌트 구현

package.json, src/App.tsx, src/components/bottomSheet/BottomSheet.stories.tsx, src/components/bottomSheet/BottomSheet.tsx, src/stores/useBottomSheetStore.ts, src/stores/utils.ts, src/styles/emotion.d.ts, src/styles/theme.ts, yarn.lock
Bottom Sheet 구현
</br>
</br>
- maxWidth 전역 스타일 추가
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #16
=> [ARV-45] Bottom Sheet 구현

.storybook/preview.tsx, src/components/badge/Badge.stories.tsx, src/components/badge/Badge.tsx, src/styles/theme.ts
Badge 구현
</br>
</br>
- theme.ts에 red bg 색상 추가
- preview.tsx에 box-sizing: border-box; 추가
</br>
</br>
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. Closes #22
=> [ARV-50] Badge 구현

.storybook/preview.tsx, package.json, src/App.tsx, tsconfig.json, vite.config.ts
emotion 설정 추가
</br>
</br>
- @emotion/babel-plugin 설치 및 vite.config.ts에 반영
- tsconfig.json에 storybook 관련 설정 추가
- App.tsx emotion css 주석 제거
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #36
=> [ARV-68] emotion 설정 추가

src/components/bottomNavigation/BottomNavigation.stories.tsx, src/components/bottomNavigation/BottomNavigation.tsx, src/components/bottomNavigation/types.ts, tsconfig.json
BottomNavigation 컴포넌트 구현
</br>
</br>
- BottomNavigation 컴포넌트 추가
</br>
</br>
</br>
</br>
- 기본 선택은 홈으로 해두었어요!
- 나중에 경로 재설정이 필요할 것 같습니다! 우선 임시로 넣어놨어요!
</br>
- Closes #35
=> [ARV-55] BottomNavigation 컴포넌트 구현

.storybook/main.ts, package.json, src/components/chips/FilterChip.stories.tsx, src/components/chips/FilterChip.tsx, src/components/chips/SimpleChip.stories.tsx, src/components/chips/SimpleChip.tsx, yarn.lock
[ARV-70] Chip width 변경
</br>
</br>
- chip width 값 변경
- @storybook/addon-actions 설치 및 적용
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #40
=> [ARV-70] Chip width 변경

src/components/bottomNav/BottomNav.tsx, src/components/checkbox/Checkbox.tsx, src/components/header/Header.tsx, src/components/radioButton/RadioButton.tsx, src/components/select/Select.tsx
px 단위 rem으로 변경
</br>
</br>
- 주요 변경 사항을 요약하여 적어주세요. 
</br>
</br>
</br>
- Closes #49
=> [ARV-75] px 단위를 rem으로 변경

.storybook/preview.tsx, src/components/badge/Badge.stories.tsx, src/components/badge/Badge.tsx, src/components/buttons/BaseButton.stories.tsx, src/components/buttons/BaseButton.tsx, src/components/buttons/IconButton.stories.tsx, src/components/chips/FilterChip.stories.tsx, src/components/chips/FilterChip.tsx, src/components/chips/SimpleChip.stories.tsx, src/components/chips/SimpleChip.tsx
컴포넌트 style 단위 px -> rem으로 변경
</br>
</br>
- 컴포넌트 style 단위를 px에서 rem으로 변경함
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #46
=> [ARV-74] 컴포넌트 style 단위 px -> rem으로 변경

src/components/bottomNav/BottomNav.tsx, src/components/topNav/TopNav.stories.tsx, src/components/topNav/TopNav.tsx, src/components/topNav/types.ts
TopNav 컴포넌트 구현
</br>
</br>
- TopNav 컴포넌트 추가
</br>
</br>
</br>
</br>
- 경로는 미지정 해놨습니다! 다음에 추가해야할 것 같아요 👍🏻
</br>
- Closes #51
=> [ARV-76] TopNav 컴포넌트 구현

src/components/subHeader/SubHeader.stories.tsx, src/components/subHeader/SubHeader.tsx
SubHeader 컴포넌트 구현
</br>
</br>
- SubHeader 컴포넌트 추가
</br>
</br>
</br>
</br>
- 뒤로가기 버튼은 우선 `navigate(-1)`로 추가해뒀습니다!
- 공유하기 기능은 url이 필요해서 배포 후에 추가로 구현해두겠습니다 🫡
</br>
- Closes #54
=> [ARV-77] SubHeader 컴포넌트 구현

src/components/counter/Counter.stories.tsx, src/components/counter/Counter.tsx
Counter 컴포넌트 구현
</br>
</br>
X
</br>
</br>
</br>
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #32
=> [ARV-58] Counter 컴포넌트 구현

src/components/searchInput/SearchInput.stories.tsx, src/components/searchInput/SearchInput.tsx
SearchInput 컴포넌트 구현
</br>
</br>
- SearchInput 컴포넌트 추가
</br>
</br>
</br>
</br>
- 검색 비활성화시 입력값이 지워지는 것을 useEffect로 처리를 해버릴지 보여지는 것만 Input 컴포넌트에서 처리해줄지 고민되네요 🥸
</br>
- Closes #57
=> [ARV-79] SearchInput 컴포넌트 구현

package.json, src/components/calendar/Calendar.stories.tsx, src/components/calendar/Calendar.tsx, src/components/calendar/types.ts, yarn.lock
Calendar 컴포넌트 구현
</br>
</br>
- react-datepicker 라이브러리 삭제
</br>
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #55
=> [ARV-78] Calendar 컴포넌트 구현

src/components/avatarUploader/AvatarUploader.stories.tsx, src/components/avatarUploader/AvatarUploader.tsx
PR의 주요 목적과 변경 사항에 대해 간단히 설명해 주세요.
</br>
</br>
- AvatarUploader 컴포넌트 추가
</br>
</br>
</br>
</br>
- image 파일 형식은 우선 `Image/*`로 해뒀어용!
</br>
- Closes #61
=> [ARV-81] AvatarUploader 컴포넌트 구현

src/components/buttons/BaseButton.tsx, src/components/buttons/IconButton.tsx, src/components/chips/FilterChip.tsx, src/components/chips/SimpleChip.tsx, src/components/counter/Counter.stories.tsx, src/components/counter/Counter.tsx, src/components/tabBar/TabBar.stories.tsx, src/components/tabBar/TabBar.tsx, src/components/tabBar/tabData.ts, src/styles/GlobalStyle.tsx
Tab Bar 컴포넌트 구현 및 GlobalStyle button style 추가
</br>
</br>
- GlobalStyle에 button 관련 style 추가
- Tab Bar 컴포넌트 구현
</br>
</br>
</br>
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #59
=> [ARV-80] Tab Bar 컴포넌트 구현 및 GlobalStyle button style 추가

package.json, src/components/buttons/BaseButton.tsx, src/components/inputField/InputField.stories.tsx, src/components/inputField/InputField.tsx, src/components/inputField/TitleInputField.stories.tsx, src/components/inputField/TitleInputField.tsx, yarn.lock
Input Field 컴포넌트 구현
</br>
</br>
- react-number-format 설치
- small size BaseButton border-radius 8px -> 4px로 변경
</br>
</br>
</br>
validation error
</br>
focus
</br>
숫자 입력, 단위 포함, 천 단위 comma
</br>
패턴(예시: 전화번호)
</br>
자동 하이픈 생성
</br>
disabled
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. Closes #67
=> [ARV-85] Input Field 컴포넌트 구현

package.json, src/main.tsx, yarn.lock
Tanstack Query 설정
</br>
</br>
- tanstack query 설치
</br>
</br>
</br>
UI 변경 사항이 있거나 테스트 관련 스크린샷이 필요한 경우 추가해 주세요.
</br>
</br>
- 관련된 이슈 번호를 참조하세요. Closes #75
=> [ARV-95] Tanstack Query 설정

src/components/searchInput/SearchInput.stories.tsx, src/components/searchInput/SearchInput.tsx
SearchInput 컴포넌트에 onSearch callback prop 기능 추가
</br>
</br>
- handleKeyDown 추가 및 onSearch prop 추가했습니다!
</br>
- handleKeyDown, onSearch
</br>
</br>
</br>
X
</br>
- Closes #65
=> [ARV-84] onSearch callback prop 추가

src/main.tsx
React Query Devtools main에 추가
</br>
</br>
- main.tsx에 ReactQueryDevtools 추가
</br>
</br>
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. Closes #82
=> [ARV-110] React Query Devtools main에 추가

.env, src/pages/concert/Concert.tsx
공연 메인페이지 layout 구현
</br>
</br>
- layout 추가
</br>
</br>
</br>
- Closes #81
=> [ARV-109] Concert page layout 구현

src/api/refundAccount.ts, src/components/buttons/BaseButton.tsx, src/constants/endPoint.ts, src/layout/TitleHeaderLayout.tsx, src/pages/editProfile/EditProfile.tsx, src/pages/myPage/MyPage.tsx, src/pages/myPage/components/AccountStatus.tsx, src/pages/myPage/components/ApplicationSection.tsx, src/pages/myPage/components/ManagementSection.tsx, src/pages/myPage/components/RefundBottomSheet.tsx, src/pages/myPage/components/UserProfile.tsx, src/types/user.ts
MyPage 페이지 구현
</br>
</br>
- BaseButton에 react-router-dom(Link) 기능 추가.
</br>
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #80
=> [ARV-103] MyPage 페이지 구현

package.json, src/constants/endPoint.ts, src/pages/home/Home.tsx, src/pages/home/components/MainPoster.tsx, yarn.lock
메인페이지 구현
</br>
</br>
- 메인페이지 구현
- swiper 라이브러리 추가
</br>
</br>
</br>
- Closes #104
=> [ARV-149] 메인 페이지 구현

src/components/inputField/InputField.tsx, src/components/message/ValidationMessage.tsx, src/constants/placeholder.ts, src/constants/toastMessage.ts, src/main.tsx, src/pages/busRental/components/RentalPostItem.tsx, src/pages/busRentalDetail/BusRentalDetail.tsx, src/pages/busRentalDetail/components/BoardingDateRadio.tsx, src/pages/busRentalDetail/components/BoardingTypeRadio.tsx, src/pages/busRentalDetail/components/DepositDialog.tsx, src/pages/busRentalDetail/components/DepositFormSheet.tsx, src/pages/busRentalDetail/components/ParticipantsStatus.tsx, src/pages/busRentalDetail/components/RadioItem.tsx, src/pages/busRentalDetail/components/RefundTypeRadio.tsx, src/pages/busRentalDetail/components/RentalInputField.tsx, src/schemas/depositFormSchema.ts, src/schemas/index.ts, src/stores/index.ts, src/stores/useDepositFormStore.ts, src/stores/useRentalFilterStore.ts, src/utils/dateUtils.ts
차량 대절 신청 폼 구현
</br>
</br>
- 주요 변경 사항을 요약하여 적어주세요. 
</br>
</br>
</br>
UI 변경 사항이 있거나 테스트 관련 스크린샷이 필요한 경우 추가해 주세요.
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #101
=> [ARV-145] 차량 대절 신청 폼 구현

src/api/surveyApi.ts, src/components/bottomSheet/BottomSheet.tsx, src/pages/surveyDetail/SurveyDetail.tsx, src/pages/surveys/Surveys.tsx, src/pages/surveys/components/SurveyItem.tsx, src/queries/survey/index.ts, src/queries/survey/useMyCreatedSurveys.ts, src/queries/survey/useSurveyList.ts, src/types/survey.ts
수요 조사 메인 페이지 구현
</br>
</br>
- bottomsheet max-height 수정
- useMyCreatedSurveyList 파일명 변경
</br>
</br>
</br>
=> [ARV-140] 수요 조사 메인 페이지 구현

src/components/avatarUploader/AvatarUploader.stories.tsx, src/components/topNav/TopNav.tsx, src/pages/busRentalDetail/components/RentalInputField.tsx, src/pages/editProfile/EditProfile.tsx, src/pages/myPage/components/RefundBottomSheet.tsx, src/pages/mySurveyManagement/MySurveyManagement.tsx, src/pages/mySurveyManagement/components/SurveyItem.tsx, src/routes/routes.tsx, src/types/survey.ts
1차 배포
</br>
</br>
- 타입 오류 수정
- route 경로 수정
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #111
=> [ARV-153] 1차 배포

src/constants/endPoint.ts, src/pages/callback/Callback.tsx, src/pages/signIn/SignIn.tsx, src/pages/signUp/SignUp.tsx, src/routes/routes.tsx, src/stores/authStore.ts
PR의 주요 목적과 변경 사항에 대해 간단히 설명해 주세요.
</br>
</br>
- 주요 변경 사항을 요약하여 적어주세요. 
</br>
</br>
</br>
UI 변경 사항이 있거나 테스트 관련 스크린샷이 필요한 경우 추가해 주세요.
</br>
</br>
- Closes #114
=> [ARV-156] 로그인 인증 개선

package.json, src/pages/openSurvey/OpenSurvey.tsx, src/pages/openSurvey/components/SearchField.tsx, vite.config.ts, yarn.lock
수요 조사 개설 페이지 UI 구현
</br>
</br>
</br>
-  Closes #117
=> [ARV-161] 수요 조사 개설 페이지 레이아웃

src/components/header/Header.tsx, src/layout/ProtectedRoutes.tsx, src/routes/routes.tsx
Protected routes 구현 및 헤더 네비게이션 uerProfile 출력
</br>
</br>
- 로그인시, Header에 유저 닉네임, 프로필 이미지 출력되도록 수정
</br>
</br>
=> [ARV-170] Protected routes 구현

src/components/calendar/Calendar.tsx, src/components/checkbox/Checkbox.tsx, src/pages/concert/components/ListItem.tsx, src/pages/openSurvey/OpenSurvey.tsx, src/pages/openSurvey/components/CalendarBottomSheet.tsx, src/pages/openSurvey/components/SelectedConcertItem.tsx, src/pages/openSurvey/type.ts, src/utils/dateUtils.ts
수요 조사 개설 페이지 기능 구현
</br>
</br>
- OpenSurvey 페이지 추가
- getDateRange util 추가
</br>
</br>
</br>
- Closes #122
=> [ARV-169] 수요 조사 개설 구현

src/components/popularKeyword/PopularKeyword.stories.tsx, src/components/popularKeyword/PopularKeyword.tsx, src/constants/endPoint.ts
PR의 주요 목적과 변경 사항에 대해 간단히 설명해 주세요.
</br>
</br>
- PopularKeyword 컴포넌트 구현
</br>
</br>
</br>
</br>
- Closes #106
=> [ARV-150] 실시간 검색어 컴포넌트 구현

src/pages/home/Home.tsx, src/pages/home/components/MainPoster.tsx, src/pages/surveys/components/SurveyItem.tsx, yarn.lock
메인페이지에 실시간 검색어 컴포넌트, 개설된 차량 수요조사 리스트를 추가
</br>
</br>
- 주요 변경 사항을 요약하여 적어주세요. 
</br>
</br>
</br>
</br>
- Closes #130
=> [ARV-176] 메인 페이지 구성 요소 추가

src/components/popularKeyword/PopularKeyword.tsx, src/constants/endPoint.ts, src/layout/SearchLayout.tsx, src/pages/home/Home.tsx, src/pages/openSurvey/OpenSurvey.tsx, src/pages/search/Search.tsx, src/pages/search/components/RecentSearch.tsx, src/pages/searchMore/SearchMoreConcerts.tsx, src/pages/searchMore/SearchMoreRents.tsx, src/pages/searchMore/SearchMoreSurveys.tsx, src/pages/searchMore/type.ts, src/pages/surveys/Surveys.tsx, src/routes/routes.tsx, src/types/search.ts
검색 페이지, 검색 결과 더보기 구현
</br>
</br>
- 검색 기록
- 검색 결과 페이지
- 결과 더보기 페이지
</br>
</br>
</br>
-Closes #132
=> [ARV-1791] 컴색 페이지 구현

src/pages/busRentalDetail/components/sheets/DepositFormSheet.tsx, src/types/rental.ts
차량 대절의 환불 계좌 타입 관련 빌드 오류 해결
</br>
</br>
X
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #142
=> [ARV-201] 차량 대절 타입 관련 빌드 오류 해결

src/components/rating/Rating.stories.tsx, src/components/rating/Rating.tsx, src/components/tabBar/TabBar.stories.tsx, src/pages/concertHallDetail/ConcertHallDetail.tsx, src/pages/concertHallDetail/components/RelatedConcert.tsx, src/pages/concertHallDetail/components/SeatReview.tsx, src/pages/concertHallDetail/components/SeatReviewItem.tsx, src/pages/concertHallDetail/components/SeatReviewSheet.tsx, src/routes/routes.tsx, src/types/concertHall.ts, src/types/index.ts, src/utils/dateUtils.ts
공연장 상세 레이아웃 구현
</br>
</br>
X
</br>
</br>
</br>
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #139
=> [ARV-190] 공연장 상세 레이아웃 구현

src/api/concertHalls.ts, src/components/topNav/TopNav.tsx, src/constants/endPoint.ts, src/pages/concertHallsList/ConcertHallsList.tsx, src/pages/concertHallsList/components/ConcertHallItem.tsx, src/pages/concertHallsList/components/FilterChips.tsx, src/pages/concertHallsList/components/ListItem.tsx, src/pages/concertHallsList/type.ts, src/routes/routes.tsx
콘서트홀 메인 페이지 구현
</br>
</br>
- 콘서트 홀 메인 페이지 router 연결
- 페이지 구현
</br>
</br>
</br>
</br>
- Closes #141
=> [ARV-200] 콘서트 홀 메인 페이지 구현

package.json, src/api/concertHallApi.ts, src/api/index.ts, src/api/rentalApi.ts, src/components/rating/Rating.tsx, src/pages/concertHallDetail/ConcertHallDetail.tsx, src/pages/concertHallDetail/components/ConcertHallMap.tsx, src/pages/concertHallDetail/components/SeatReviewItem.tsx, src/queries/concertHall/index.ts, src/queries/concertHall/useGetConcertHallDetail.ts, src/types/concertHall.ts, tsconfig.json, yarn.lock
공연장 상세 페이지 연동
</br>
</br>
X
</br>
</br>
</br>
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #145
=> [ARV-205] 공연장 상세 페이지 연동

src/api/concertHallApi.ts, src/constants/endPoint.ts, src/pages/concertHallDetail/ConcertHallDetail.tsx, src/pages/concertHallDetail/components/ConcertHallMap.tsx, src/pages/concertHallDetail/components/RelatedConcert.tsx, src/pages/concertHallDetail/components/SeatReview.tsx, src/pages/concertHallDetail/components/SeatReviewItem.tsx, src/queries/concertHall/index.ts, src/queries/concertHall/useGetConcertHallDetail.ts, src/queries/concertHall/useGetRelateConcert.ts, src/queries/concertHall/useGetSeatReviews.ts, src/routes/routes.tsx, src/types/concertHall.ts
좌석 리뷰 및 관련 공연 API 연동
</br>
</br>
- 공연장 상세 페이지에 좌석 리뷰, 관련 공연 API 연동
</br>
</br>
</br>
X
</br>
X
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #151
=> [ARV-211] 좌석 리뷰 및 관련 공연 API 연동

src/api/authApi.ts, src/components/header/Header.tsx, src/constants/endPoint.ts, src/hooks/useLoginCheck.ts, src/pages/myPage/MyPage.tsx, src/stores/authStore.ts
로그아웃 기능 추가
</br>
</br>
- 로그인 버튼 리렌더링 되는 이유로 userInfo sessionStorage 사용하도록 수정
</br>
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #162
=> [ARV-230] 로그아웃 기능 추가

src/components/items/SearchArtistItem.tsx, src/components/sheets/SearchArtistSheet.tsx, src/pages/openBusRental/components/sections/DetailFormInfo.tsx, src/pages/signUp/SignUp.tsx, src/pages/signUp/components/ArtistSelector.tsx, src/schemas/userProfileSchema.ts, src/types/search.ts, src/types/user.ts
회원가입 페이지 아티스트 검색 추가 및 폼 전송 오류 해결
</br>
</br>
- 아티스트 검색 컴포넌트 수정
</br>
</br>
</br>
X
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #159
=> [ARV-228] 회원가입 페이지 아티스트 검색 추가 및 폼 전송 오류 해결

src/components/header/Header.tsx, src/queries/user/useGetUserInfo.ts, src/stores/authStore.ts
로그인 유지 오류 수정
</br>
</br>
- 로그인 유지 오류 수정
</br>
</br>
=> [ARV-233] 로그인 유지 오류 수정

public/mockServiceWorker.js, src/api/index.ts, src/api/rentalApi.ts, src/api/rentalFormApi.ts, src/components/bottomNav/BottomNav.tsx, src/components/inputField/InputField.tsx, src/components/inputField/TitleInputField.tsx, src/components/message/ValidationMessage.tsx, src/components/sheets/SearchConcertSheet.tsx, src/constants/placeholder.ts, src/pages/busRentalDetail/components/sheets/DepositFormSheet.tsx, src/pages/openBusRental/components/items/RentalInputField.tsx, src/pages/openBusRental/components/items/RentalTextArea.tsx, src/pages/openBusRental/components/items/RentalThumbField.tsx, src/pages/openBusRental/components/items/RentalTitleField.tsx, src/pages/openBusRental/components/modal/FormSubmitDialog.tsx, src/pages/openBusRental/components/sections/DetailFormInfo.tsx, src/queries/rentForm/usePostRentalForm.ts, src/schemas/rentalFormSchema.ts, src/stores/rentalFormStore.ts, src/types/rentalForm.ts, src/utils/rentalFormUtils.ts, yarn.lock
차량 대절 폼에 presigned url 적용
</br>
</br>
- 주요 변경 사항을 요약하여 적어주세요.
</br>
</br>
</br>
x
</br>
</br>
- 관련된 이슈 번호를 참조하세요. 예: Closes #165
=> [ARV-231] 차량 대절 폼에 presigned url 적용
